author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Li Qingrong"
  pronouns         : # example: "she/her"
  bio              : "Data Science and Big Data Technology, Fuzhou University"
  location         : "Fujian, China"
  employer         : "Fuzhou University"
  uri              : # URL
  email            :

  # Academic websites
  academia         : # URL
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    :
  inspire-hep      : # URL
  impactstory      : # URL
  orcid            :
  semantic         : # URL
  ssrn             : # URL
  pubmed           :
  researchgate     : # URL
  scopus           : # URL
  zotero           : # URL


  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "opqrst121100"
  kaggle           : # Username
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")

  # Social media
  artstation       : # Username
  bluesky          :
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : # Username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username for X / Twitter
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # Username
